version: "1"
rules:                               # Array of rules
  - base: develop                    # Required. Target branch
    upstream: getferdi:develop       # Required. Must be in the same fork network.
    mergeMethod: hardreset           # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: master
    upstream: getferdi:master        # Required. Can be a branch in the same forked repo.
    assignees:
      - Makazzz
    reviewers:
      - Makazzz
label: ":arrow_heading_down: pull"
